config/routes.rb
Rails.application.routes.draw do
  get 'web_scrappers/index'
  root to:"travels#index"
  resources :web_scrappings
  resources :falsh_way_mappings
  resources :travels
  devise_for :users
  resources :web_scrappers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/falsh_way_mapping.rb
class FalshWayMapping < ApplicationRecord
end

app/models/travel.rb
class Travel < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/web_scrapper.rb
class WebScrapper < Kimurai::Base

	@name = "web_scrapper_spider"
	@engine = :mechanize
	@start_urls = ["https://metaruby.com/"]
	@config = {
	user_agent: "Chrome/68.0.3440.84"
	}

	def parse(response, url:, data: { })
	blogs = []
	puts response.xpath("//table[@class='topic-list']//tbody//tr")
	response.xpath("//table[@class='topic-list']//tbody//tr").each do |tr|
	scrapped_data = {
	                title: tr.at('td[1]//span').text,
	                category: tr.at('td[1]//div//span').text,
	                date: tr.at('td[3]').text.strip
	              }
	blogs << scrapped_data
	save_to "results.json", scrapped_data.as_json, format: :json
	end
	end
end

app/models/web_scrapping.rb
class WebScrapping < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/falsh_way_mappings_controller.rb
class FalshWayMappingsController < ApplicationController
  before_action :set_falsh_way_mapping, only: %i[ show edit update destroy ]

  # GET /falsh_way_mappings or /falsh_way_mappings.json
  def index
    @falsh_way_mappings = FalshWayMapping.all
  end

  # GET /falsh_way_mappings/1 or /falsh_way_mappings/1.json
  def show
  end

  # GET /falsh_way_mappings/new
  def new
    @falsh_way_mapping = FalshWayMapping.new
  end

  # GET /falsh_way_mappings/1/edit
  def edit
  end

  # POST /falsh_way_mappings or /falsh_way_mappings.json
  def create
    @falsh_way_mapping = FalshWayMapping.new(falsh_way_mapping_params)

    respond_to do |format|
      if @falsh_way_mapping.save
        format.html { redirect_to falsh_way_mapping_url(@falsh_way_mapping), notice: "Falsh way mapping was successfully created." }
        format.json { render :show, status: :created, location: @falsh_way_mapping }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @falsh_way_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /falsh_way_mappings/1 or /falsh_way_mappings/1.json
  def update
    respond_to do |format|
      if @falsh_way_mapping.update(falsh_way_mapping_params)
        format.html { redirect_to falsh_way_mapping_url(@falsh_way_mapping), notice: "Falsh way mapping was successfully updated." }
        format.json { render :show, status: :ok, location: @falsh_way_mapping }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @falsh_way_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /falsh_way_mappings/1 or /falsh_way_mappings/1.json
  def destroy
    @falsh_way_mapping.destroy

    respond_to do |format|
      format.html { redirect_to falsh_way_mappings_url, notice: "Falsh way mapping was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_falsh_way_mapping
      @falsh_way_mapping = FalshWayMapping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def falsh_way_mapping_params
      params.fetch(:falsh_way_mapping, {})
    end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /travels or /travels.json
  def index
    @travels = Travel.all
  end

  # GET /travels/1 or /travels/1.json
  def show
  end

  # GET /travels/new
  def new
    @travel = Travel.new
  end

  # GET /travels/1/edit
  def edit
  end

  # POST /travels or /travels.json
  def create
    @travel = Travel.new(travel_params)

    respond_to do |format|
      if @travel.save
        format.html { redirect_to travel_url(@travel), notice: "Travel was successfully created." }
        format.json { render :show, status: :created, location: @travel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travels/1 or /travels/1.json
  def update
    respond_to do |format|
      if @travel.update(travel_params)
        format.html { redirect_to travel_url(@travel), notice: "Travel was successfully updated." }
        format.json { render :show, status: :ok, location: @travel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1 or /travels/1.json
  def destroy
    @travel.destroy

    respond_to do |format|
      format.html { redirect_to travels_url, notice: "Travel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel
      @travel = Travel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def travel_params
      params.fetch(:travel, {})
    end
end

app/controllers/web_scrappers_controller.rb
class WebScrappersController < ApplicationController
  def index
  end
  def new
    WebScrapper.crawl!
  end
end

app/controllers/web_scrappings_controller.rb
class WebScrappingsController < ApplicationController
  before_action :set_web_scrapping, only: %i[ show edit update destroy ]

  # GET /web_scrappings or /web_scrappings.json
  def index
    @web_scrappings = WebScrapping.all
  end

  # GET /web_scrappings/1 or /web_scrappings/1.json
  def show
  end

  # GET /web_scrappings/new
  def new
    @web_scrapping = WebScrapping.new
  end

  # GET /web_scrappings/1/edit
  def edit
  end

  # POST /web_scrappings or /web_scrappings.json
  def create
    @web_scrapping = WebScrapping.new(web_scrapping_params)

    respond_to do |format|
      if @web_scrapping.save
        format.html { redirect_to web_scrapping_url(@web_scrapping), notice: "Web scrapping was successfully created." }
        format.json { render :show, status: :created, location: @web_scrapping }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @web_scrapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /web_scrappings/1 or /web_scrappings/1.json
  def update
    respond_to do |format|
      if @web_scrapping.update(web_scrapping_params)
        format.html { redirect_to web_scrapping_url(@web_scrapping), notice: "Web scrapping was successfully updated." }
        format.json { render :show, status: :ok, location: @web_scrapping }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @web_scrapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_scrappings/1 or /web_scrappings/1.json
  def destroy
    @web_scrapping.destroy

    respond_to do |format|
      format.html { redirect_to web_scrappings_url, notice: "Web scrapping was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web_scrapping
      @web_scrapping = WebScrapping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def web_scrapping_params
      params.fetch(:web_scrapping, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/falsh_way_mappings_helper.rb
module FalshWayMappingsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/web_scrappers_helper.rb
module WebScrappersHelper
end

app/helpers/web_scrappings_helper.rb
module WebScrappingsHelper
end

app/views/falsh_way_mappings/_form.html.erb
<%= form_with(model: falsh_way_mapping, local: true) do |form| %>
  <% if falsh_way_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(falsh_way_mapping.errors.count, "error") %> prohibited this falsh_way_mapping from being saved:</h2>

      <ul>
        <% falsh_way_mapping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/falsh_way_mappings/edit.html.erb
<h1>Editing Falsh Way Mapping</h1>

<%= render 'form', falsh_way_mapping: @falsh_way_mapping %>

<%= link_to 'Show', @falsh_way_mapping %> |
<%= link_to 'Back', falsh_way_mappings_path %>

app/views/falsh_way_mappings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Falsh Way Mappings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @falsh_way_mappings.each do |falsh_way_mapping| %>
      <tr>
        <td><%= link_to 'Show', falsh_way_mapping %></td>
        <td><%= link_to 'Edit', edit_falsh_way_mapping_path(falsh_way_mapping) %></td>
        <td><%= link_to 'Destroy', falsh_way_mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Falsh Way Mapping', new_falsh_way_mapping_path %>

app/views/falsh_way_mappings/new.html.erb
<h1>New Falsh Way Mapping</h1>

<%= render 'form', falsh_way_mapping: @falsh_way_mapping %>

<%= link_to 'Back', falsh_way_mappings_path %>

app/views/falsh_way_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_falsh_way_mapping_path(@falsh_way_mapping) %> |
<%= link_to 'Back', falsh_way_mappings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BitlaFlashWay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "font-awesome/css/all.css", media:"all" %>
    <%= stylesheet_link_tag "style.css", media:"all" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/travels/_dashboard.html.erb
<div class="row">
<section class="vh-10 rounded bg-light shadow m-3 col">
         <div class="container-fluid pt-4 px-4 p-5">
                <div class="row">
                  <div class="col col-ml-12">
                    <h2>Scrapping</h2>
                  </div>
                </div>
                <div class="row g-4 ">
                    <div class="col cursor">
                        <div class="bg-primary rounded d-flex align-items-center justify-content-center p-4 text-white">                            
                            
                                <i class="bg-primary rounded fa-solid fa-train fa-2xl"></i>                            
                            
                        </div>
                    </div>
                    <div class="col  cursor">
                        <div class="bg-primary rounded d-flex align-items-center justify-content-center p-4 text-white">                            
                            
                                <i class="fa-solid fa-plane-departure fa-2xl"></i>                           
                           
                        </div>
                    </div>
                    <div class="col cursor">
                        <div class="bg-primary rounded d-flex align-items-center justify-content-center p-4 text-white">                            
                            
                                <i class="fa-solid fa-bus-simple fa-2xl"></i>                            
                           
                        </div>
                    </div>                                  
                </div>
            </div>
        </section>
       
        <section class="vh-10 rounded bg-light shadow m-3 col">
          <div class="container-fluid pt-4 px-4 p-5">
                <div class="row">
                  <div class="col col-ml-12">
                    <h2>API's</h2>
                  </div>
                </div>
                <div class="row g-4">
                    <div class="col cursor">
                        <div class="bg-primary rounded d-flex align-items-center justify-content-center p-4 text-white">                            
                            
                                <i class="bg-primary rounded fa-solid fa-train fa-2xl"></i>                            
                            
                        </div>
                    </div>
                    <div class="col  cursor">
                        <div class="bg-primary rounded d-flex align-items-center justify-content-center p-4 text-white">                            
                            
                                <i class="fa-solid fa-plane-departure fa-2xl"></i>                           
                           
                        </div>
                    </div>
                    <div class="col cursor">
                        <div class="bg-primary rounded d-flex align-items-center justify-content-center p-4 text-white">                            
                            
                                <i class="fa-solid fa-bus-simple fa-2xl"></i>                            
                           
                        </div>
                    </div>                                    
                </div>
            </div>
        </section>
</div>

<div class="row">
         <section class="vh-10 rounded bg-light shadow-sm mt-3 col">
          <div class="container-fluid pt-4 px-4">
          <div class="row">
          <div class="col">
                    <h2>FLASH WAY DATA</h2>
            </div>
            <!-- <div class="col">
                  <button type="button" class="btn btn-primary cursor">Update operators</button>
            </div> -->            
          </div>
          <div class="row shadow-sm">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Resource</th>
                  <th scope="col">Date</th>
                  <th scope="col">Data</th>
                  <th scope="col">Description</th>
                  <th scope="col">Type</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>Make My Trip</td>
                  <td>12/6/2022</td>
                  <td>""[{:origin=>\"Banglaore\", :destination=>\"Hyedrabad\"",...."</td>
                  <td></td>
                  <td>Web Scraped</td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                   <td>Make My Trip</td>
                  <td>13/6/2022</td>
                  <td>""[{:origin=>\"Banglaore\", :destination=>\"Mangalore\",...."</td>
                  <td></td>
                  <td>Api</td>
                </tr>
               <tr>
                  <th scope="row">3</th>
                  <td>IRCTC</td>
                  <td>14/6/2022</td>
                  <td>""[{:origin=>\"Banglaore\", :destination=>\"Chennai\", :,...."</td>
                  <td></td>
                  <td>Api</td>
                </tr>
                <tr>
                  <th scope="row">4</th>
                   <td>GOOGLE CALANDER</td>
                  <td>15/6/2022</td>
                  <td>""[{:origin=>\"Banglaore\", :destination=>\"Chennai\", ,...."</td>
                  <td></td>
                  <td>Api</td>
                </tr>
              </tbody>
            </table>
          </div>
          </div>
        </section>
         <section class="vh-10 rounded bg-light shadow-sm mt-3 col">
          <div class="container-fluid pt-4 px-4">
          <div class="row">
          <div class="col">
                    <h2>SYNCED DATA</h2>
            </div>
            <!-- <div class="col">
                  <button type="button" class="btn btn-primary cursor">Update operators</button>
            </div>   -->          
          </div>
          <div class="row shadow-sm">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Syned On</th>
                  <th scope="col">Resource</th>
                  <th scope="col">Operator</th>
                  <th scope="col">Remarks</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>12/7/2022</td>
                  <td>Make My Trip</td>
                  <td>BITLA TRAVELS</td>
                  <td></td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                   <td>15/7/2022</td>
                  <td>IRCTC</td>
                  <td>BITLA TRAVELS</td>
                  <td>Train cancelled due to heavy rains in Bangalore</td>
                </tr>
               <tr>
                  <th scope="row">3</th>
                   <td>16/7/2022</td>
                  <td>MAKE MY TRIP</td>
                  <td>BITLA TRAVELS</td>
                  <td>Flight schedule postponed due to weather conditions</td>
                </tr>
                <tr>
                  <th scope="row">4</th>
                   <td>17/7/2022</td>
                  <td>YELLOW TRAVELS</td>
                  <td>BITLA TRAVELS</td>
                  <td>Bus schedule cancelled due to low occupancy</td>
                </tr>
              </tbody>
            </table>
          </div>
          </div>
        </section>
<section class="vh-10 rounded bg-light shadow-sm mt-3 col">
          <div class="container-fluid pt-4 px-4">
          <div class="row">
          <div class="col">
                    <h2>MAPPED TRAVELS</h2>
            </div>
            <!-- <div class="col">
                  <button type="button" class="btn btn-primary cursor">Update operators</button>
            </div>  -->           
          </div>
          <div class="row shadow-sm">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Operator</th>
                  <th scope="col">Email</th>
                  <th scope="col">Phone Number</th>
                  <th scope="col">Flash Way</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>BITLA TRAVELS</td>
                  <td>Bitla@bitlasoft.com</td>
                  <td>(080-234567278)</td>
                  <td>Approved</td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                   <td>RED TRAVELS</td>
                  <td>red@redtravels.com</td>
                  <td>(080-234567278)</td>
                  <td>Approved</td>
                </tr>
               <tr>
                  <th scope="row">3</th>
                   <td>YELLOW TRAVELS</td>
                  <td>yellow@yellowtravels.com</td>
                  <td>(080-234567278)</td>
                  <td>Pending</td>
                </tr>
                <tr>
                  <th scope="row">4</th>
                   <td>BLUE TRAVELS</td>
                  <td>Blue@bluetravels.com</td>
                  <td>(080-789555222)</td>
                  <td>Pending</td>
                </tr>
              </tbody>
            </table>
          </div>
          </div>
        </section>
</div>
       

app/views/travels/_form.html.erb
<%= form_with(model: travel, local: true) do |form| %>
  <% if travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul>
        <% travel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/travels/_operator.html.erb
<div class="modal fade" id="license" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Bitla Flash Way Aggrement</h5>        
      </div>
      <div class="modal-body">
        <h5 class="modal-title">TERMS OF SERVICE AGREEMENT</h5>

            <p>LAST REVISION: [18-07-2022]</p>
            PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.
            This Terms of Service Agreement (the "Agreement") governs your use of this website, [www.bitlaflashway.com]  offer of products for purchase on this Website, or your purchase of products available on this Website. This Agreement includes, and incorporates by this reference, the policies and guidelines referenced below. [Business Name] reserves the right to change or revise the terms and conditions of this Agreement at any time by posting any changes or a revised Agreement on this Website. [Business Name] will alert you that changes or revisions have been made by indicating on the top of this Agreement the date it was last revised. The changed or revised Agreement will be effective immediately after it is posted on this Website, please immediately terminate your use of the Website. If you would like to print this Agreement, please click the print button on your browser toolbar.
            
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">I Don't</button>
        <button type="button" class="btn btn-primary" onclick="showContent();">I Accept</button>
      </div>
    </div>
  </div>
</div>

<section class="vh-10 rounded bg-light shadow-sm mt-3 col" id="op_content" style="display:none">
          <div class="container-fluid pt-4 px-4">
          <div class="row mb-4">
          <div class="col ">
                    <!-- <h2>Results</h2> -->
            </div>
            <div class="col text-right">
                  <button type="button" class="btn btn-primary cursor">Flash Way Data</button>
            </div>            
          </div>
          <div class="row shadow-sm">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Date</th>
                  <th scope="col">Origin</th>
                  <th scope="col">Destination</th>
                  <th scope="col">Remarks</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>11/06/2022</td>
                  <td>Bangalore</td>
                  <td>Chennai</td>
                  <td>Train cancelled due to heavy rains in Bangalore</td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                   <td>10/6/2022</td>
                  <td>Bangalore</td>
                  <td>Hyderabad</td>
                  <td>Train cancelled due to heavy rains in Bangalore</td>
                </tr>
               <tr>
                  <th scope="row">3</th>
                   <td>9/6/2022</td>
                  <td>Bangalore</td>
                  <td>Pune</td>
                  <td>Flight schedule postponed due to weather conditions</td>
                </tr>
                <tr>
                  <th scope="row">4</th>
                   <td>08/6/2022</td>
                  <td>Bangalore</td>
                  <td>Pune</td>
                  <td>Bus schedule cancelled due to low occupancy</td>
                </tr>
              </tbody>
            </table>
          </div>
          </div>
        </section>
<script>
$('#license').modal();
function showContent(){
  $('#license').modal("hide");
  $('#op_content').show();
}
</script>

app/views/travels/edit.html.erb
<h1>Editing Travel</h1>

<%= render 'form', travel: @travel %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>

app/views/travels/index.html.erb
<style>
.cursor{
  cursor:pointer
}
</style>
<div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar" class="active">
        <h1><a href="#" class="logo">B.</a></h1>
        <ul class="list-unstyled components mb-5">
            <li class="active">
                <a href="#"><span class="fa fa-home"></span> Dashboard</a>
            </li>
        </ul>
        <div class="footer">
            <p>
                Copyright ©
                <script>document.write(new Date().getYear());</script>2022 All rights reserved | This template is
                made with <i class="icon-heart" aria-hidden="true"></i> by <b>Bitla</b>
            </p>
        </div>
    </nav>
  
    <div id="content" class="p-4 p-md-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">                
                <h2 class="fw-normal ml-4" style="letter-spacing: 1px;"><%= current_user.email.to_s == ("shiv.prasad215@gmail.com") ? "BITLA TRAVELS" : "BITLA FLASH WAY" %></h2>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                    <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active">
                            <a class="nav-link" href="#"><i class="fa-solid fa-circle-user"></i> &nbsp;&nbsp;<%=current_user.email%>  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></a>                            
                        </li>
                        <li class="nav-item active">
                            <%#= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
        <%if !(current_user.email == "shiv.prasad215@gmail.com")%>
        <%= render :partial => "travels/dashboard" %>
        <%else%>
        <%= render :partial => "travels/operator" %>
        <%end%>
    </div>
</div>

app/views/travels/new.html.erb
<h1>New Travel</h1>

<%= render 'form', travel: @travel %>

<%= link_to 'Back', travels_path %>

app/views/travels/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_travel_path(@travel) %> |
<%= link_to 'Back', travels_path %>

app/views/web_scrappers/index.html.erb
<h1>WebScrappers#index</h1>
<p>Find me in app/views/web_scrappers/index.html.erb</p>


<%= link_to 'Start Scrap', new_web_scrapper_path %>

app/views/web_scrappings/_form.html.erb
<%= form_with(model: web_scrapping, local: true) do |form| %>
  <% if web_scrapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web_scrapping.errors.count, "error") %> prohibited this web_scrapping from being saved:</h2>

      <ul>
        <% web_scrapping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/web_scrappings/edit.html.erb
<h1>Editing Web Scrapping</h1>

<%= render 'form', web_scrapping: @web_scrapping %>

<%= link_to 'Show', @web_scrapping %> |
<%= link_to 'Back', web_scrappings_path %>

app/views/web_scrappings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Web Scrappings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @web_scrappings.each do |web_scrapping| %>
      <tr>
        <td><%= link_to 'Show', web_scrapping %></td>
        <td><%= link_to 'Edit', edit_web_scrapping_path(web_scrapping) %></td>
        <td><%= link_to 'Destroy', web_scrapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web Scrapping', new_web_scrapping_path %>

app/views/web_scrappings/new.html.erb
<h1>New Web Scrapping</h1>

<%= render 'form', web_scrapping: @web_scrapping %>

<%= link_to 'Back', web_scrappings_path %>

app/views/web_scrappings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_web_scrapping_path(@web_scrapping) %> |
<%= link_to 'Back', web_scrappings_path %>